Input add is clearable; expand disabled theme
xcritical-software/xc-front-kit pull request #309
Opened 2020-12-29 11:49 UTC by SergeyBondar93

2020-12-30 11:16 UTC, Pavel0408 approved these changes

2020-12-30 15:03 UTC, lusd commented on packages/input/src/Input.tsx
> +  const [focus, setFocus] = useState(false);
minor: since it's boolean, suggesting to use 'isFocused' instead of 'focus'

2020-12-30 15:33 UTC, lusd commented on packages/input/src/utils/getStyles.ts
> +  const invalidtHover = css`
minor: misstype invalid**t**Hover

2020-12-30 15:39 UTC, lusd submitted a review, later dismissed

2020-12-30 16:27 UTC, Pavel0408 submitted a review, later dismissed

2021-01-08 13:58 UTC, sonya569 commented on packages/input/src/utils/getStyles.ts
> +    ${standartFocus}
minor: standart => standard

2021-01-08 14:00 UTC, sonya569 submitted a review, later dismissed

2021-01-11 07:21 UTC, tundraray requested changes

2021-01-11 07:21 UTC, tundraray commented on packages/input/src/interfaces.ts
> +  focusOnInput?: boolean;
are you sure this is needed here? This type defines the public properties of the input, not the inside

2021-01-11 08:05 UTC, tundraray approved these changes

2021-01-11 08:06 UTC, merged