feat(input): add styles for type=number
xcritical-software/xc-front-kit pull request #322
Opened 2021-02-19 15:30 UTC by scrymetto

Add new prop to remove arrows

2021-02-24 13:02 UTC, tundraray requested changes

2021-02-24 13:02 UTC, tundraray commented on packages/input/src/Input.tsx
> +  isArrowsHidden = false,
I think the arrow should be hidden by default. And prop name can be called like showArrows.

2021-02-25 14:35 UTC, lusd approved these changes

2021-03-02 11:09 UTC, tema1411 approved these changes

2021-03-02 16:52 UTC, tundraray approved these changes

2021-03-02 16:53 UTC, tundraray approved these changes

2021-03-02 17:21 UTC, merged